#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

from config import (
    COLORS,
    COMPONENTS_PDF_DIR,
    COMPONENTS_SVG_DIR,
    COMPONENT_BASENAMES,
    FIGURE_OUT_DIR,
    get_derived_layout,
    PROCESSED_DIR,
    REQUIRED_PROCESSED_FOR_COMPILE,
    REQUIRED_TIKZ_FILES,
    TIKZ_COLOR_MAP,
    TIKZ_DIR,
    ensure_output_dirs,
)


def require_command(cmd: str) -> None:
    if shutil.which(cmd) is None:
        raise RuntimeError(f"Required executable not found in PATH: {cmd}")


def verify_assets() -> None:
    missing: list[str] = []
    for name in REQUIRED_PROCESSED_FOR_COMPILE:
        path = PROCESSED_DIR / name
        if not path.exists():
            missing.append(str(path))
    for basename in COMPONENT_BASENAMES:
        path = COMPONENTS_PDF_DIR / f"{basename}.pdf"
        if not path.exists():
            missing.append(str(path))
    for source in REQUIRED_TIKZ_FILES:
        if not source.exists():
            missing.append(str(source))
    if missing:
        joined = "\n  - ".join(missing)
        raise FileNotFoundError(f"Missing assets/source files:\n  - {joined}")


def verify_tikz_sources_only() -> None:
    missing = [str(path) for path in REQUIRED_TIKZ_FILES if not path.exists()]
    if missing:
        joined = "\n  - ".join(missing)
        raise FileNotFoundError(f"Missing TikZ source files:\n  - {joined}")


def write_asset_paths_tex() -> Path:
    """Derive asset dirs from config paths; write relative paths for XeLaTeX."""
    target = TIKZ_DIR / "asset_paths.tex"
    # Compute paths relative to the tikz/ directory (where pdflatex runs)
    tikz = TIKZ_DIR

    def rel(p: Path) -> str:
        # Use os.path.relpath to get correct '../outputs' style paths
        import os
        return os.path.relpath(p, tikz)

    lines = [
        "% Auto-generated by scripts/03_compile_figure.py\n",
        f"\\def\\ProcessedDir{{{rel(PROCESSED_DIR)}}}\n",
        f"\\def\\ComponentsSvgDir{{{rel(COMPONENTS_SVG_DIR)}}}\n",
        f"\\def\\ComponentsPdfDir{{{rel(COMPONENTS_PDF_DIR)}}}\n",
        f"\\def\\FigureOutDir{{{rel(FIGURE_OUT_DIR)}}}\n",
    ]
    target.write_text("".join(lines), encoding="utf-8")
    print(f"[compile] wrote {target.relative_to(TIKZ_DIR.parent)}")
    return target


def write_generated_colors_tex() -> Path:
    """Write tikz/generated_colors.tex from config.COLORS + TIKZ_COLOR_MAP."""
    target = TIKZ_DIR / "generated_colors.tex"
    lines = [
        "% Auto-generated by scripts/03_compile_figure.py — do not edit by hand.\n",
        "% Edit config.py:COLORS / TIKZ_COLOR_MAP and re-run make.\n",
    ]
    for py_key, tikz_name in TIKZ_COLOR_MAP.items():
        r, g, b = COLORS[py_key]
        lines.append(f"\\definecolor{{{tikz_name}}}{{RGB}}{{{r},{g},{b}}}\n")

    # Color-utility macros
    lines.append("\n% --- Color utility macros (auto-generated) ---\n")
    for py_key, tikz_name in TIKZ_COLOR_MAP.items():
        short = py_key.replace("_", "").capitalize()
        lines.append(f"\\newcommand{{\\{short}Text}}{{\\color{{{tikz_name}}}}}\n")
        lines.append(f"\\newcommand{{\\{short}Bg}}{{\\colorbox{{{tikz_name}}}}}\n")

    target.write_text("".join(lines), encoding="utf-8")
    print(f"[compile] wrote {target.relative_to(TIKZ_DIR.parent)}")
    return target


def write_generated_layout_tex() -> Path:
    """Write tikz/generated_layout.tex from config.get_derived_layout()."""
    target = TIKZ_DIR / "generated_layout.tex"
    lines = [
        "% Auto-generated by scripts/03_compile_figure.py — do not edit by hand.\n",
        "% Edit config.py:ATOMIC_LAYOUT and re-run make.\n",
    ]
    for key, val in get_derived_layout().items():
        lines.append(f"\\def\\{key}{{{val}}}\n")
    target.write_text("".join(lines), encoding="utf-8")
    print(f"[compile] wrote {target.relative_to(TIKZ_DIR.parent)}")
    return target


def run_command(cmd: list[str], *, cwd: Path) -> None:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        tail = "\n".join(proc.stdout.splitlines()[-120:])
        raise RuntimeError(
            f"Command failed ({proc.returncode}): {' '.join(cmd)}\n\n{tail}"
        )


def compile_pdf(*, n_passes: int) -> Path:
    require_command("pdflatex")
    cmd = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "figure.tex"]
    for index in range(1, n_passes + 1):
        run_command(cmd, cwd=TIKZ_DIR)
        print(f"[compile] pdflatex pass {index}/{n_passes}")

    built_pdf = TIKZ_DIR / "figure.pdf"
    if not built_pdf.exists():
        raise FileNotFoundError(f"Expected compiled PDF not found: {built_pdf}")

    output_pdf = FIGURE_OUT_DIR / "jaxent_figure.pdf"
    shutil.copy2(built_pdf, output_pdf)
    print(f"[compile] wrote {output_pdf.relative_to(TIKZ_DIR.parent)}")
    return output_pdf


def export_png(pdf_path: Path, *, dpi: int) -> Path | None:
    output = FIGURE_OUT_DIR / "jaxent_figure.png"
    if shutil.which("pdftoppm"):
        stem = output.with_suffix("")
        run_command(
            [
                "pdftoppm",
                "-singlefile",
                "-png",
                "-r",
                str(dpi),
                str(pdf_path),
                str(stem),
            ],
            cwd=FIGURE_OUT_DIR,
        )
        print(f"[compile] wrote {output.relative_to(TIKZ_DIR.parent)}")
        return output

    if shutil.which("gs"):
        run_command(
            [
                "gs",
                "-dNOPAUSE",
                "-dBATCH",
                "-sDEVICE=pngalpha",
                f"-r{dpi}",
                f"-sOutputFile={output}",
                str(pdf_path),
            ],
            cwd=FIGURE_OUT_DIR,
        )
        print(f"[compile] wrote {output.relative_to(TIKZ_DIR.parent)}")
        return output

    print("[compile] skipped PNG export (pdftoppm/gs not found)")
    return None


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate assets, write TikZ path macros, and compile final figure."
    )
    parser.add_argument(
        "--tikz-only",
        action="store_true",
        help="Compile TikZ layout without requiring Script 1/2 asset checks.",
    )
    parser.add_argument(
        "--skip-verify",
        action="store_true",
        help="Skip all input validation checks.",
    )
    parser.add_argument("--passes", type=int, default=2)
    parser.add_argument("--no-png", action="store_true")
    parser.add_argument("--dpi", type=int, default=300)
    args = parser.parse_args()

    if args.passes < 1:
        raise ValueError("--passes must be >= 1.")

    ensure_output_dirs()

    if not args.skip_verify:
        if args.tikz_only:
            verify_tikz_sources_only()
        else:
            verify_assets()

    write_asset_paths_tex()
    write_generated_colors_tex()
    write_generated_layout_tex()
    pdf = compile_pdf(n_passes=args.passes)
    if not args.no_png:
        export_png(pdf, dpi=args.dpi)


if __name__ == "__main__":
    main()
